name: ci


on:
  push:
    paths:
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -DBUILD_TESTING=on
    - run: cmake --build --preset default
    - run: ctest --preset default

  macos:
    runs-on: macos-latest
    needs: linux
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -DBUILD_TESTING=on
    - run: cmake --build --preset default
    - run: ctest --preset default

  windows:
    runs-on: windows-latest
    needs: linux
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -DBUILD_TESTING=on
    - run: cmake --build --preset default
    - run: ctest --preset default -C Debug
